// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package api_test

import (
	"context"
	"sync"

	"github.com/zorcal/sbgfit/backend/api"
	"github.com/zorcal/sbgfit/backend/internal/core/mdl"
)

// Ensure, that MockedExerciseServiced does implement api.ExerciseService.
// If this is not the case, regenerate this file with moq.
var _ api.ExerciseService = &MockedExerciseServiced{}

// MockedExerciseServiced is a mock implementation of api.ExerciseService.
//
//	func TestSomethingThatUsesExerciseService(t *testing.T) {
//
//		// make and configure a mocked api.ExerciseService
//		mockedExerciseService := &MockedExerciseServiced{
//			ExercisesFunc: func(ctx context.Context, fltr mdl.ExerciseFilter, pageSize int, pageNumber int) ([]mdl.Exercise, int, error) {
//				panic("mock out the Exercises method")
//			},
//		}
//
//		// use mockedExerciseService in code that requires api.ExerciseService
//		// and then make assertions.
//
//	}
type MockedExerciseServiced struct {
	// ExercisesFunc mocks the Exercises method.
	ExercisesFunc func(ctx context.Context, fltr mdl.ExerciseFilter, pageSize int, pageNumber int) ([]mdl.Exercise, int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Exercises holds details about calls to the Exercises method.
		Exercises []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fltr is the fltr argument value.
			Fltr mdl.ExerciseFilter
			// PageSize is the pageSize argument value.
			PageSize int
			// PageNumber is the pageNumber argument value.
			PageNumber int
		}
	}
	lockExercises sync.RWMutex
}

// Exercises calls ExercisesFunc.
func (mock *MockedExerciseServiced) Exercises(ctx context.Context, fltr mdl.ExerciseFilter, pageSize int, pageNumber int) ([]mdl.Exercise, int, error) {
	if mock.ExercisesFunc == nil {
		panic("MockedExerciseServiced.ExercisesFunc: method is nil but ExerciseService.Exercises was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Fltr       mdl.ExerciseFilter
		PageSize   int
		PageNumber int
	}{
		Ctx:        ctx,
		Fltr:       fltr,
		PageSize:   pageSize,
		PageNumber: pageNumber,
	}
	mock.lockExercises.Lock()
	mock.calls.Exercises = append(mock.calls.Exercises, callInfo)
	mock.lockExercises.Unlock()
	return mock.ExercisesFunc(ctx, fltr, pageSize, pageNumber)
}

// ExercisesCalls gets all the calls that were made to Exercises.
// Check the length with:
//
//	len(mockedExerciseService.ExercisesCalls())
func (mock *MockedExerciseServiced) ExercisesCalls() []struct {
	Ctx        context.Context
	Fltr       mdl.ExerciseFilter
	PageSize   int
	PageNumber int
} {
	var calls []struct {
		Ctx        context.Context
		Fltr       mdl.ExerciseFilter
		PageSize   int
		PageNumber int
	}
	mock.lockExercises.RLock()
	calls = mock.calls.Exercises
	mock.lockExercises.RUnlock()
	return calls
}
