// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package api

import (
	"context"
	"sync"

	"github.com/zorcal/sbgfit/backend/internal/core/mdl"
)

// Ensure, that MockedExerciseServiced does implement ExerciseService.
// If this is not the case, regenerate this file with moq.
var _ ExerciseService = &MockedExerciseServiced{}

// MockedExerciseServiced is a mock implementation of ExerciseService.
//
//	func TestSomethingThatUsesExerciseService(t *testing.T) {
//
//		// make and configure a mocked ExerciseService
//		mockedExerciseService := &MockedExerciseServiced{
//			ExercisesFunc: func(ctx context.Context, fltr mdl.ExerciseFilter) ([]mdl.Exercise, error) {
//				panic("mock out the Exercises method")
//			},
//		}
//
//		// use mockedExerciseService in code that requires ExerciseService
//		// and then make assertions.
//
//	}
type MockedExerciseServiced struct {
	// ExercisesFunc mocks the Exercises method.
	ExercisesFunc func(ctx context.Context, fltr mdl.ExerciseFilter) ([]mdl.Exercise, error)

	// calls tracks calls to the methods.
	calls struct {
		// Exercises holds details about calls to the Exercises method.
		Exercises []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fltr is the fltr argument value.
			Fltr mdl.ExerciseFilter
		}
	}
	lockExercises sync.RWMutex
}

// Exercises calls ExercisesFunc.
func (mock *MockedExerciseServiced) Exercises(ctx context.Context, fltr mdl.ExerciseFilter) ([]mdl.Exercise, error) {
	if mock.ExercisesFunc == nil {
		panic("MockedExerciseServiced.ExercisesFunc: method is nil but ExerciseService.Exercises was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Fltr mdl.ExerciseFilter
	}{
		Ctx:  ctx,
		Fltr: fltr,
	}
	mock.lockExercises.Lock()
	mock.calls.Exercises = append(mock.calls.Exercises, callInfo)
	mock.lockExercises.Unlock()
	return mock.ExercisesFunc(ctx, fltr)
}

// ExercisesCalls gets all the calls that were made to Exercises.
// Check the length with:
//
//	len(mockedExerciseService.ExercisesCalls())
func (mock *MockedExerciseServiced) ExercisesCalls() []struct {
	Ctx  context.Context
	Fltr mdl.ExerciseFilter
} {
	var calls []struct {
		Ctx  context.Context
		Fltr mdl.ExerciseFilter
	}
	mock.lockExercises.RLock()
	calls = mock.calls.Exercises
	mock.lockExercises.RUnlock()
	return calls
}
