version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - depguard
    - durationcheck
    - embeddedstructfieldcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - godoclint
    - godot
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - intrange
    - iotamixing
    - ireturn
    - makezero
    - mirror
    - misspell
    - modernize
    - musttag
    - nakedret
    - nilnil
    - noctx
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - recvcheck
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
    - wrapcheck
  settings:
    misspell:
      # Correct spellings using locale preferences for US or UK.
      # Setting locale to US will correct the British spelling of 'colour' to 'color'.
      # Default is to use a neutral variety of English.
      locale: US
    nakedret:
      max-func-lines: 0
    sloglint:
      context: "all"
      msg-style: capitalized
      key-naming-case: snake
      forbidden-keys:
        - time
        - level
        - msg
        - source
    staticcheck:
      http-status-code-whitelist: []
      checks: ["all"]
    tagliatelle:
      case:
        rules:
          json: camel
          env: upperSnake
          envconfig: upperSnake
    errcheck:
      check-type-assertions: true
      check-blank: true
      # List of functions to exclude from checking, where each entry is a single function to exclude.
      # See https://github.com/kisielk/errcheck#excluding-functions for details.
      exclude-functions:
        - fmt.Fprint
        - (*net/http.Server).Close
        - (*github.com/jackc/pgx/v5/pgxpool.Pool).Query
        - (net/http.ResponseWriter).Write
      verbose: true
    gosec:
      excludes:
        - G104 # Handled by errcheck
    depguard:
      rules:
        main:
          list-mode: "strict"
          allow:
            - $gostd
            - github.com/zorcal/sbgfit/backend
            - github.com/ardanlabs/conf/v3
            - github.com/lmittmann/tint
            - github.com/google/uuid
            - github.com/jackc/pgx/v5
            - github.com/jackc/pgx/v5/pgxpool
            - github.com/amacneil/dbmate/v2/pkg/dbmate
            - github.com/amacneil/dbmate/v2/pkg/driver/postgres
            - github.com/google/go-cmp/cmp
            - github.com/google/go-cmp/cmp/cmpopts
            - github.com/ogen-go/ogen/middleware
            - github.com/go-faster/jx
            - github.com/ogen-go/ogen/ogenerrors
            - go.opentelemetry.io/otel
            - go.opentelemetry.io/otel/attribute
            - go.opentelemetry.io/otel/baggage
            - go.opentelemetry.io/otel/codes
            - go.opentelemetry.io/otel/trace
            - go.opentelemetry.io/otel/propagation
            - go.opentelemetry.io/otel/sdk/trace
            - go.opentelemetry.io/otel/sdk/resource
            - go.opentelemetry.io/otel/exporters/stdout/stdouttrace
            - go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp
            - go.opentelemetry.io/otel/semconv/v1.17.0
            - go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc
            - github.com/pgx-contrib/pgxotel
            - google.golang.org/grpc
            - google.golang.org/grpc/credentials/insecure
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - generic
        # Allow api type to return ogen interfaces
        - "github.com/zorcal/sbgfit/backend/api/internal/openapi.*"
        # Allow OpenTelemetry interfaces
        - "go.opentelemetry.io/otel/trace.*"
    wrapcheck:
      ignore-sigs:
        - fmt.Errorf
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Write(
  exclusions:
    rules:
      - path: main\.go
        linters:
          - contextcheck
      - path: _test\.go
        linters:
          - errcheck
          - bodyclose
          - unparam
      - path: internal/telemetry/telemetry\.go
        linters:
          - spancheck # Telemetry utility functions intentionally return spans for caller to manage
formatters:
  enable:
    - gci
    - gofumpt
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/zorcal/sbgfit/backend)
        - blank
        - dot
        - alias
        - localmodule
    gofumpt:
      extra-rules: true
    golines:
      max-len: 200
      tab-len: 4
      shorten-comments: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
