version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - depguard
    - durationcheck
    - embeddedstructfieldcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - godoclint
    - godot
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - intrange
    - iotamixing
    - ireturn
    - makezero
    - mirror
    - misspell
    - modernize
    - musttag
    - nakedret
    - nilnil
    - noctx
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - recvcheck
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
    - wrapcheck
  settings:
    misspell:
      # Correct spellings using locale preferences for US or UK.
      # Setting locale to US will correct the British spelling of 'colour' to 'color'.
      # Default is to use a neutral variety of English.
      locale: US
    nakedret:
      max-func-lines: 0
    sloglint:
      context: "all"
      msg-style: capitalized
      key-naming-case: snake
      forbidden-keys:
        - time
        - level
        - msg
        - source
    staticcheck:
      http-status-code-whitelist: []
      checks: ["all"]
    tagliatelle:
      case:
        rules:
          json: camel
          env: upperSnake
          envconfig: upperSnake
    errcheck:
      check-type-assertions: true
      check-blank: true
      # List of functions to exclude from checking, where each entry is a single function to exclude.
      # See https://github.com/kisielk/errcheck#excluding-functions for details.
      exclude-functions:
        - fmt.Fprint
        - (*net/http.Server).Close
      verbose: true
    gosec:
      excludes:
        - G104 # Handled by other errcheck
    depguard:
      rules:
        main:
          list-mode: "strict"
          allow:
            - $gostd
            - github.com/zorcal/sbgfit/backend
            - github.com/ardanlabs/conf/v3
            - github.com/lmittmann/tint
            - github.com/google/uuid
            - github.com/jackc/pgx/v5/pgxpool
            - github.com/amacneil/dbmate/v2/pkg/dbmate
            - github.com/amacneil/dbmate/v2/pkg/driver/postgres
    wrapcheck:
      ignore-sigs:
        - fmt.Errorf
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Write(

formatters:
  enable:
    - gci
    - gofumpt
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/zorcal/sbgfit/backend)
        - blank
        - dot
        - alias
        - localmodule
    gofumpt:
      extra-rules: true
    golines:
      max-len: 200
      tab-len: 4
      shorten-comments: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
