// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s *Exercise) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Category.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "category",
			Error: err,
		})
	}
	if err := func() error {
		if s.EquipmentTypes == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.EquipmentTypes {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "equipmentTypes",
			Error: err,
		})
	}
	if err := func() error {
		if s.PrimaryMuscles == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.PrimaryMuscles {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "primaryMuscles",
			Error: err,
		})
	}
	if err := func() error {
		if s.Tags == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Tags {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "tags",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ExerciseCategory) Validate() error {
	switch s {
	case "cardio":
		return nil
	case "strength":
		return nil
	case "plyometric":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s ExerciseEquipmentTypesItem) Validate() error {
	switch s {
	case "bodyweight":
		return nil
	case "kettlebell":
		return nil
	case "rowing-machine":
		return nil
	case "ski-erg":
		return nil
	case "medicine-ball":
		return nil
	case "dumbbells":
		return nil
	case "barbell":
		return nil
	case "sled":
		return nil
	case "box":
		return nil
	case "jump-rope":
		return nil
	case "assault-bike":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s ExercisePrimaryMusclesItem) Validate() error {
	switch s {
	case "chest":
		return nil
	case "back":
		return nil
	case "shoulders":
		return nil
	case "biceps":
		return nil
	case "triceps":
		return nil
	case "forearms":
		return nil
	case "core":
		return nil
	case "abs":
		return nil
	case "obliques":
		return nil
	case "glutes":
		return nil
	case "quads":
		return nil
	case "hamstrings":
		return nil
	case "calves":
		return nil
	case "legs":
		return nil
	case "full-body":
		return nil
	case "grip":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *ExerciseResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Data == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Data {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ExerciseTagsItem) Validate() error {
	switch s {
	case "crossfit":
		return nil
	case "hyrox":
		return nil
	case "beginner-friendly":
		return nil
	case "advanced":
		return nil
	case "conditioning":
		return nil
	case "strength-endurance":
		return nil
	case "power":
		return nil
	case "core":
		return nil
	case "functional":
		return nil
	case "competition":
		return nil
	case "plyometric":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s GetExercisesCategory) Validate() error {
	switch s {
	case "cardio":
		return nil
	case "strength":
		return nil
	case "plyometric":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
