// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"math/bits"
	"strconv"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/json"
	"github.com/ogen-go/ogen/validate"
)

// Encode encodes EquipmentType as json.
func (s EquipmentType) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes EquipmentType from json.
func (s *EquipmentType) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode EquipmentType to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch EquipmentType(v) {
	case EquipmentTypeBodyweight:
		*s = EquipmentTypeBodyweight
	case EquipmentTypeKettlebell:
		*s = EquipmentTypeKettlebell
	case EquipmentTypeRowingMachine:
		*s = EquipmentTypeRowingMachine
	case EquipmentTypeSkiErg:
		*s = EquipmentTypeSkiErg
	case EquipmentTypeMedicineBall:
		*s = EquipmentTypeMedicineBall
	case EquipmentTypeDumbbells:
		*s = EquipmentTypeDumbbells
	case EquipmentTypeBarbell:
		*s = EquipmentTypeBarbell
	case EquipmentTypeSled:
		*s = EquipmentTypeSled
	case EquipmentTypeBox:
		*s = EquipmentTypeBox
	case EquipmentTypeJumpRope:
		*s = EquipmentTypeJumpRope
	case EquipmentTypeAssaultBike:
		*s = EquipmentTypeAssaultBike
	default:
		*s = EquipmentType(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s EquipmentType) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *EquipmentType) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *ErrorResponse) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *ErrorResponse) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("error")
		e.Str(s.Error)
	}
}

var jsonFieldsNameOfErrorResponse = [1]string{
	0: "error",
}

// Decode decodes ErrorResponse from json.
func (s *ErrorResponse) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode ErrorResponse to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "error":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				v, err := d.Str()
				s.Error = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"error\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode ErrorResponse")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00000001,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfErrorResponse) {
					name = jsonFieldsNameOfErrorResponse[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *ErrorResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ErrorResponse) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *Exercise) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *Exercise) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("id")
		json.EncodeUUID(e, s.ID)
	}
	{
		e.FieldStart("name")
		e.Str(s.Name)
	}
	{
		e.FieldStart("category")
		s.Category.Encode(e)
	}
	{
		if s.Description.Set {
			e.FieldStart("description")
			s.Description.Encode(e)
		}
	}
	{
		if s.Instructions != nil {
			e.FieldStart("instructions")
			e.ArrStart()
			for _, elem := range s.Instructions {
				e.Str(elem)
			}
			e.ArrEnd()
		}
	}
	{
		e.FieldStart("equipmentTypes")
		e.ArrStart()
		for _, elem := range s.EquipmentTypes {
			elem.Encode(e)
		}
		e.ArrEnd()
	}
	{
		e.FieldStart("primaryMuscles")
		e.ArrStart()
		for _, elem := range s.PrimaryMuscles {
			elem.Encode(e)
		}
		e.ArrEnd()
	}
	{
		e.FieldStart("tags")
		e.ArrStart()
		for _, elem := range s.Tags {
			elem.Encode(e)
		}
		e.ArrEnd()
	}
	{
		e.FieldStart("createdAt")
		json.EncodeDateTime(e, s.CreatedAt)
	}
	{
		e.FieldStart("updatedAt")
		json.EncodeDateTime(e, s.UpdatedAt)
	}
}

var jsonFieldsNameOfExercise = [10]string{
	0: "id",
	1: "name",
	2: "category",
	3: "description",
	4: "instructions",
	5: "equipmentTypes",
	6: "primaryMuscles",
	7: "tags",
	8: "createdAt",
	9: "updatedAt",
}

// Decode decodes Exercise from json.
func (s *Exercise) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode Exercise to nil")
	}
	var requiredBitSet [2]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "id":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				v, err := json.DecodeUUID(d)
				s.ID = v
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"id\"")
			}
		case "name":
			requiredBitSet[0] |= 1 << 1
			if err := func() error {
				v, err := d.Str()
				s.Name = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"name\"")
			}
		case "category":
			requiredBitSet[0] |= 1 << 2
			if err := func() error {
				if err := s.Category.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"category\"")
			}
		case "description":
			if err := func() error {
				s.Description.Reset()
				if err := s.Description.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"description\"")
			}
		case "instructions":
			if err := func() error {
				s.Instructions = make([]string, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem string
					v, err := d.Str()
					elem = string(v)
					if err != nil {
						return err
					}
					s.Instructions = append(s.Instructions, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"instructions\"")
			}
		case "equipmentTypes":
			requiredBitSet[0] |= 1 << 5
			if err := func() error {
				s.EquipmentTypes = make([]EquipmentType, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem EquipmentType
					if err := elem.Decode(d); err != nil {
						return err
					}
					s.EquipmentTypes = append(s.EquipmentTypes, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"equipmentTypes\"")
			}
		case "primaryMuscles":
			requiredBitSet[0] |= 1 << 6
			if err := func() error {
				s.PrimaryMuscles = make([]PrimaryMuscle, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem PrimaryMuscle
					if err := elem.Decode(d); err != nil {
						return err
					}
					s.PrimaryMuscles = append(s.PrimaryMuscles, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"primaryMuscles\"")
			}
		case "tags":
			requiredBitSet[0] |= 1 << 7
			if err := func() error {
				s.Tags = make([]ExerciseTag, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem ExerciseTag
					if err := elem.Decode(d); err != nil {
						return err
					}
					s.Tags = append(s.Tags, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"tags\"")
			}
		case "createdAt":
			requiredBitSet[1] |= 1 << 0
			if err := func() error {
				v, err := json.DecodeDateTime(d)
				s.CreatedAt = v
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"createdAt\"")
			}
		case "updatedAt":
			requiredBitSet[1] |= 1 << 1
			if err := func() error {
				v, err := json.DecodeDateTime(d)
				s.UpdatedAt = v
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"updatedAt\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode Exercise")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [2]uint8{
		0b11100111,
		0b00000011,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfExercise) {
					name = jsonFieldsNameOfExercise[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *Exercise) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *Exercise) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes ExerciseCategory as json.
func (s ExerciseCategory) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes ExerciseCategory from json.
func (s *ExerciseCategory) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode ExerciseCategory to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch ExerciseCategory(v) {
	case ExerciseCategoryCardio:
		*s = ExerciseCategoryCardio
	case ExerciseCategoryStrength:
		*s = ExerciseCategoryStrength
	case ExerciseCategoryPlyometric:
		*s = ExerciseCategoryPlyometric
	default:
		*s = ExerciseCategory(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s ExerciseCategory) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ExerciseCategory) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *ExerciseResponse) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *ExerciseResponse) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("data")
		e.ArrStart()
		for _, elem := range s.Data {
			elem.Encode(e)
		}
		e.ArrEnd()
	}
	{
		e.FieldStart("total")
		e.Int(s.Total)
	}
}

var jsonFieldsNameOfExerciseResponse = [2]string{
	0: "data",
	1: "total",
}

// Decode decodes ExerciseResponse from json.
func (s *ExerciseResponse) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode ExerciseResponse to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "data":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				s.Data = make([]Exercise, 0)
				if err := d.Arr(func(d *jx.Decoder) error {
					var elem Exercise
					if err := elem.Decode(d); err != nil {
						return err
					}
					s.Data = append(s.Data, elem)
					return nil
				}); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"data\"")
			}
		case "total":
			requiredBitSet[0] |= 1 << 1
			if err := func() error {
				v, err := d.Int()
				s.Total = int(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"total\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode ExerciseResponse")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00000011,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfExerciseResponse) {
					name = jsonFieldsNameOfExerciseResponse[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *ExerciseResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ExerciseResponse) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes ExerciseTag as json.
func (s ExerciseTag) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes ExerciseTag from json.
func (s *ExerciseTag) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode ExerciseTag to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch ExerciseTag(v) {
	case ExerciseTagCrossfit:
		*s = ExerciseTagCrossfit
	case ExerciseTagHyrox:
		*s = ExerciseTagHyrox
	case ExerciseTagBeginnerFriendly:
		*s = ExerciseTagBeginnerFriendly
	case ExerciseTagAdvanced:
		*s = ExerciseTagAdvanced
	case ExerciseTagConditioning:
		*s = ExerciseTagConditioning
	case ExerciseTagStrengthEndurance:
		*s = ExerciseTagStrengthEndurance
	case ExerciseTagPower:
		*s = ExerciseTagPower
	case ExerciseTagCore:
		*s = ExerciseTagCore
	case ExerciseTagFunctional:
		*s = ExerciseTagFunctional
	case ExerciseTagCompetition:
		*s = ExerciseTagCompetition
	case ExerciseTagPlyometric:
		*s = ExerciseTagPlyometric
	default:
		*s = ExerciseTag(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s ExerciseTag) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ExerciseTag) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes string as json.
func (o OptNilString) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	if o.Null {
		e.Null()
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes string from json.
func (o *OptNilString) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptNilString to nil")
	}
	if d.Next() == jx.Null {
		if err := d.Null(); err != nil {
			return err
		}

		var v string
		o.Value = v
		o.Set = true
		o.Null = true
		return nil
	}
	o.Set = true
	o.Null = false
	v, err := d.Str()
	if err != nil {
		return err
	}
	o.Value = string(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptNilString) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNilString) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes PrimaryMuscle as json.
func (s PrimaryMuscle) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes PrimaryMuscle from json.
func (s *PrimaryMuscle) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode PrimaryMuscle to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch PrimaryMuscle(v) {
	case PrimaryMuscleChest:
		*s = PrimaryMuscleChest
	case PrimaryMuscleBack:
		*s = PrimaryMuscleBack
	case PrimaryMuscleShoulders:
		*s = PrimaryMuscleShoulders
	case PrimaryMuscleBiceps:
		*s = PrimaryMuscleBiceps
	case PrimaryMuscleTriceps:
		*s = PrimaryMuscleTriceps
	case PrimaryMuscleForearms:
		*s = PrimaryMuscleForearms
	case PrimaryMuscleCore:
		*s = PrimaryMuscleCore
	case PrimaryMuscleAbs:
		*s = PrimaryMuscleAbs
	case PrimaryMuscleObliques:
		*s = PrimaryMuscleObliques
	case PrimaryMuscleGlutes:
		*s = PrimaryMuscleGlutes
	case PrimaryMuscleQuads:
		*s = PrimaryMuscleQuads
	case PrimaryMuscleHamstrings:
		*s = PrimaryMuscleHamstrings
	case PrimaryMuscleCalves:
		*s = PrimaryMuscleCalves
	case PrimaryMuscleLegs:
		*s = PrimaryMuscleLegs
	case PrimaryMuscleFullBody:
		*s = PrimaryMuscleFullBody
	case PrimaryMuscleGrip:
		*s = PrimaryMuscleGrip
	default:
		*s = PrimaryMuscle(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s PrimaryMuscle) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *PrimaryMuscle) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}
