// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *ErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/EquipmentType
type EquipmentType string

const (
	EquipmentTypeBodyweight    EquipmentType = "bodyweight"
	EquipmentTypeKettlebell    EquipmentType = "kettlebell"
	EquipmentTypeRowingMachine EquipmentType = "rowing-machine"
	EquipmentTypeSkiErg        EquipmentType = "ski-erg"
	EquipmentTypeMedicineBall  EquipmentType = "medicine-ball"
	EquipmentTypeDumbbells     EquipmentType = "dumbbells"
	EquipmentTypeBarbell       EquipmentType = "barbell"
	EquipmentTypeSled          EquipmentType = "sled"
	EquipmentTypeBox           EquipmentType = "box"
	EquipmentTypeJumpRope      EquipmentType = "jump-rope"
	EquipmentTypeAssaultBike   EquipmentType = "assault-bike"
)

// AllValues returns all EquipmentType values.
func (EquipmentType) AllValues() []EquipmentType {
	return []EquipmentType{
		EquipmentTypeBodyweight,
		EquipmentTypeKettlebell,
		EquipmentTypeRowingMachine,
		EquipmentTypeSkiErg,
		EquipmentTypeMedicineBall,
		EquipmentTypeDumbbells,
		EquipmentTypeBarbell,
		EquipmentTypeSled,
		EquipmentTypeBox,
		EquipmentTypeJumpRope,
		EquipmentTypeAssaultBike,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s EquipmentType) MarshalText() ([]byte, error) {
	switch s {
	case EquipmentTypeBodyweight:
		return []byte(s), nil
	case EquipmentTypeKettlebell:
		return []byte(s), nil
	case EquipmentTypeRowingMachine:
		return []byte(s), nil
	case EquipmentTypeSkiErg:
		return []byte(s), nil
	case EquipmentTypeMedicineBall:
		return []byte(s), nil
	case EquipmentTypeDumbbells:
		return []byte(s), nil
	case EquipmentTypeBarbell:
		return []byte(s), nil
	case EquipmentTypeSled:
		return []byte(s), nil
	case EquipmentTypeBox:
		return []byte(s), nil
	case EquipmentTypeJumpRope:
		return []byte(s), nil
	case EquipmentTypeAssaultBike:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *EquipmentType) UnmarshalText(data []byte) error {
	switch EquipmentType(data) {
	case EquipmentTypeBodyweight:
		*s = EquipmentTypeBodyweight
		return nil
	case EquipmentTypeKettlebell:
		*s = EquipmentTypeKettlebell
		return nil
	case EquipmentTypeRowingMachine:
		*s = EquipmentTypeRowingMachine
		return nil
	case EquipmentTypeSkiErg:
		*s = EquipmentTypeSkiErg
		return nil
	case EquipmentTypeMedicineBall:
		*s = EquipmentTypeMedicineBall
		return nil
	case EquipmentTypeDumbbells:
		*s = EquipmentTypeDumbbells
		return nil
	case EquipmentTypeBarbell:
		*s = EquipmentTypeBarbell
		return nil
	case EquipmentTypeSled:
		*s = EquipmentTypeSled
		return nil
	case EquipmentTypeBox:
		*s = EquipmentTypeBox
		return nil
	case EquipmentTypeJumpRope:
		*s = EquipmentTypeJumpRope
		return nil
	case EquipmentTypeAssaultBike:
		*s = EquipmentTypeAssaultBike
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

func (*ErrorResponse) getExercisesRes() {}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// Ref: #/components/schemas/Exercise
type Exercise struct {
	ID             uuid.UUID        `json:"id"`
	Name           string           `json:"name"`
	Category       ExerciseCategory `json:"category"`
	Description    OptNilString     `json:"description"`
	Instructions   []string         `json:"instructions"`
	EquipmentTypes []EquipmentType  `json:"equipmentTypes"`
	PrimaryMuscles []PrimaryMuscle  `json:"primaryMuscles"`
	Tags           []ExerciseTag    `json:"tags"`
	CreatedAt      time.Time        `json:"createdAt"`
	UpdatedAt      time.Time        `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Exercise) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Exercise) GetName() string {
	return s.Name
}

// GetCategory returns the value of Category.
func (s *Exercise) GetCategory() ExerciseCategory {
	return s.Category
}

// GetDescription returns the value of Description.
func (s *Exercise) GetDescription() OptNilString {
	return s.Description
}

// GetInstructions returns the value of Instructions.
func (s *Exercise) GetInstructions() []string {
	return s.Instructions
}

// GetEquipmentTypes returns the value of EquipmentTypes.
func (s *Exercise) GetEquipmentTypes() []EquipmentType {
	return s.EquipmentTypes
}

// GetPrimaryMuscles returns the value of PrimaryMuscles.
func (s *Exercise) GetPrimaryMuscles() []PrimaryMuscle {
	return s.PrimaryMuscles
}

// GetTags returns the value of Tags.
func (s *Exercise) GetTags() []ExerciseTag {
	return s.Tags
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Exercise) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Exercise) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Exercise) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Exercise) SetName(val string) {
	s.Name = val
}

// SetCategory sets the value of Category.
func (s *Exercise) SetCategory(val ExerciseCategory) {
	s.Category = val
}

// SetDescription sets the value of Description.
func (s *Exercise) SetDescription(val OptNilString) {
	s.Description = val
}

// SetInstructions sets the value of Instructions.
func (s *Exercise) SetInstructions(val []string) {
	s.Instructions = val
}

// SetEquipmentTypes sets the value of EquipmentTypes.
func (s *Exercise) SetEquipmentTypes(val []EquipmentType) {
	s.EquipmentTypes = val
}

// SetPrimaryMuscles sets the value of PrimaryMuscles.
func (s *Exercise) SetPrimaryMuscles(val []PrimaryMuscle) {
	s.PrimaryMuscles = val
}

// SetTags sets the value of Tags.
func (s *Exercise) SetTags(val []ExerciseTag) {
	s.Tags = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Exercise) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Exercise) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// Ref: #/components/schemas/ExerciseCategory
type ExerciseCategory string

const (
	ExerciseCategoryCardio     ExerciseCategory = "cardio"
	ExerciseCategoryStrength   ExerciseCategory = "strength"
	ExerciseCategoryPlyometric ExerciseCategory = "plyometric"
)

// AllValues returns all ExerciseCategory values.
func (ExerciseCategory) AllValues() []ExerciseCategory {
	return []ExerciseCategory{
		ExerciseCategoryCardio,
		ExerciseCategoryStrength,
		ExerciseCategoryPlyometric,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ExerciseCategory) MarshalText() ([]byte, error) {
	switch s {
	case ExerciseCategoryCardio:
		return []byte(s), nil
	case ExerciseCategoryStrength:
		return []byte(s), nil
	case ExerciseCategoryPlyometric:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ExerciseCategory) UnmarshalText(data []byte) error {
	switch ExerciseCategory(data) {
	case ExerciseCategoryCardio:
		*s = ExerciseCategoryCardio
		return nil
	case ExerciseCategoryStrength:
		*s = ExerciseCategoryStrength
		return nil
	case ExerciseCategoryPlyometric:
		*s = ExerciseCategoryPlyometric
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ExerciseResponse
type ExerciseResponse struct {
	Data []Exercise `json:"data"`
	// Total number of exercises available.
	Total int `json:"total"`
}

// GetData returns the value of Data.
func (s *ExerciseResponse) GetData() []Exercise {
	return s.Data
}

// GetTotal returns the value of Total.
func (s *ExerciseResponse) GetTotal() int {
	return s.Total
}

// SetData sets the value of Data.
func (s *ExerciseResponse) SetData(val []Exercise) {
	s.Data = val
}

// SetTotal sets the value of Total.
func (s *ExerciseResponse) SetTotal(val int) {
	s.Total = val
}

func (*ExerciseResponse) getExercisesRes() {}

// Ref: #/components/schemas/ExerciseTag
type ExerciseTag string

const (
	ExerciseTagCrossfit          ExerciseTag = "crossfit"
	ExerciseTagHyrox             ExerciseTag = "hyrox"
	ExerciseTagBeginnerFriendly  ExerciseTag = "beginner-friendly"
	ExerciseTagAdvanced          ExerciseTag = "advanced"
	ExerciseTagConditioning      ExerciseTag = "conditioning"
	ExerciseTagStrengthEndurance ExerciseTag = "strength-endurance"
	ExerciseTagPower             ExerciseTag = "power"
	ExerciseTagCore              ExerciseTag = "core"
	ExerciseTagFunctional        ExerciseTag = "functional"
	ExerciseTagCompetition       ExerciseTag = "competition"
	ExerciseTagPlyometric        ExerciseTag = "plyometric"
)

// AllValues returns all ExerciseTag values.
func (ExerciseTag) AllValues() []ExerciseTag {
	return []ExerciseTag{
		ExerciseTagCrossfit,
		ExerciseTagHyrox,
		ExerciseTagBeginnerFriendly,
		ExerciseTagAdvanced,
		ExerciseTagConditioning,
		ExerciseTagStrengthEndurance,
		ExerciseTagPower,
		ExerciseTagCore,
		ExerciseTagFunctional,
		ExerciseTagCompetition,
		ExerciseTagPlyometric,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ExerciseTag) MarshalText() ([]byte, error) {
	switch s {
	case ExerciseTagCrossfit:
		return []byte(s), nil
	case ExerciseTagHyrox:
		return []byte(s), nil
	case ExerciseTagBeginnerFriendly:
		return []byte(s), nil
	case ExerciseTagAdvanced:
		return []byte(s), nil
	case ExerciseTagConditioning:
		return []byte(s), nil
	case ExerciseTagStrengthEndurance:
		return []byte(s), nil
	case ExerciseTagPower:
		return []byte(s), nil
	case ExerciseTagCore:
		return []byte(s), nil
	case ExerciseTagFunctional:
		return []byte(s), nil
	case ExerciseTagCompetition:
		return []byte(s), nil
	case ExerciseTagPlyometric:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ExerciseTag) UnmarshalText(data []byte) error {
	switch ExerciseTag(data) {
	case ExerciseTagCrossfit:
		*s = ExerciseTagCrossfit
		return nil
	case ExerciseTagHyrox:
		*s = ExerciseTagHyrox
		return nil
	case ExerciseTagBeginnerFriendly:
		*s = ExerciseTagBeginnerFriendly
		return nil
	case ExerciseTagAdvanced:
		*s = ExerciseTagAdvanced
		return nil
	case ExerciseTagConditioning:
		*s = ExerciseTagConditioning
		return nil
	case ExerciseTagStrengthEndurance:
		*s = ExerciseTagStrengthEndurance
		return nil
	case ExerciseTagPower:
		*s = ExerciseTagPower
		return nil
	case ExerciseTagCore:
		*s = ExerciseTagCore
		return nil
	case ExerciseTagFunctional:
		*s = ExerciseTagFunctional
		return nil
	case ExerciseTagCompetition:
		*s = ExerciseTagCompetition
		return nil
	case ExerciseTagPlyometric:
		*s = ExerciseTagPlyometric
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptExerciseCategory returns new OptExerciseCategory with value set to v.
func NewOptExerciseCategory(v ExerciseCategory) OptExerciseCategory {
	return OptExerciseCategory{
		Value: v,
		Set:   true,
	}
}

// OptExerciseCategory is optional ExerciseCategory.
type OptExerciseCategory struct {
	Value ExerciseCategory
	Set   bool
}

// IsSet returns true if OptExerciseCategory was set.
func (o OptExerciseCategory) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptExerciseCategory) Reset() {
	var v ExerciseCategory
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptExerciseCategory) SetTo(v ExerciseCategory) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptExerciseCategory) Get() (v ExerciseCategory, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptExerciseCategory) Or(d ExerciseCategory) ExerciseCategory {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PrimaryMuscle
type PrimaryMuscle string

const (
	PrimaryMuscleChest      PrimaryMuscle = "chest"
	PrimaryMuscleBack       PrimaryMuscle = "back"
	PrimaryMuscleShoulders  PrimaryMuscle = "shoulders"
	PrimaryMuscleBiceps     PrimaryMuscle = "biceps"
	PrimaryMuscleTriceps    PrimaryMuscle = "triceps"
	PrimaryMuscleForearms   PrimaryMuscle = "forearms"
	PrimaryMuscleCore       PrimaryMuscle = "core"
	PrimaryMuscleAbs        PrimaryMuscle = "abs"
	PrimaryMuscleObliques   PrimaryMuscle = "obliques"
	PrimaryMuscleGlutes     PrimaryMuscle = "glutes"
	PrimaryMuscleQuads      PrimaryMuscle = "quads"
	PrimaryMuscleHamstrings PrimaryMuscle = "hamstrings"
	PrimaryMuscleCalves     PrimaryMuscle = "calves"
	PrimaryMuscleLegs       PrimaryMuscle = "legs"
	PrimaryMuscleFullBody   PrimaryMuscle = "full-body"
	PrimaryMuscleGrip       PrimaryMuscle = "grip"
)

// AllValues returns all PrimaryMuscle values.
func (PrimaryMuscle) AllValues() []PrimaryMuscle {
	return []PrimaryMuscle{
		PrimaryMuscleChest,
		PrimaryMuscleBack,
		PrimaryMuscleShoulders,
		PrimaryMuscleBiceps,
		PrimaryMuscleTriceps,
		PrimaryMuscleForearms,
		PrimaryMuscleCore,
		PrimaryMuscleAbs,
		PrimaryMuscleObliques,
		PrimaryMuscleGlutes,
		PrimaryMuscleQuads,
		PrimaryMuscleHamstrings,
		PrimaryMuscleCalves,
		PrimaryMuscleLegs,
		PrimaryMuscleFullBody,
		PrimaryMuscleGrip,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PrimaryMuscle) MarshalText() ([]byte, error) {
	switch s {
	case PrimaryMuscleChest:
		return []byte(s), nil
	case PrimaryMuscleBack:
		return []byte(s), nil
	case PrimaryMuscleShoulders:
		return []byte(s), nil
	case PrimaryMuscleBiceps:
		return []byte(s), nil
	case PrimaryMuscleTriceps:
		return []byte(s), nil
	case PrimaryMuscleForearms:
		return []byte(s), nil
	case PrimaryMuscleCore:
		return []byte(s), nil
	case PrimaryMuscleAbs:
		return []byte(s), nil
	case PrimaryMuscleObliques:
		return []byte(s), nil
	case PrimaryMuscleGlutes:
		return []byte(s), nil
	case PrimaryMuscleQuads:
		return []byte(s), nil
	case PrimaryMuscleHamstrings:
		return []byte(s), nil
	case PrimaryMuscleCalves:
		return []byte(s), nil
	case PrimaryMuscleLegs:
		return []byte(s), nil
	case PrimaryMuscleFullBody:
		return []byte(s), nil
	case PrimaryMuscleGrip:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PrimaryMuscle) UnmarshalText(data []byte) error {
	switch PrimaryMuscle(data) {
	case PrimaryMuscleChest:
		*s = PrimaryMuscleChest
		return nil
	case PrimaryMuscleBack:
		*s = PrimaryMuscleBack
		return nil
	case PrimaryMuscleShoulders:
		*s = PrimaryMuscleShoulders
		return nil
	case PrimaryMuscleBiceps:
		*s = PrimaryMuscleBiceps
		return nil
	case PrimaryMuscleTriceps:
		*s = PrimaryMuscleTriceps
		return nil
	case PrimaryMuscleForearms:
		*s = PrimaryMuscleForearms
		return nil
	case PrimaryMuscleCore:
		*s = PrimaryMuscleCore
		return nil
	case PrimaryMuscleAbs:
		*s = PrimaryMuscleAbs
		return nil
	case PrimaryMuscleObliques:
		*s = PrimaryMuscleObliques
		return nil
	case PrimaryMuscleGlutes:
		*s = PrimaryMuscleGlutes
		return nil
	case PrimaryMuscleQuads:
		*s = PrimaryMuscleQuads
		return nil
	case PrimaryMuscleHamstrings:
		*s = PrimaryMuscleHamstrings
		return nil
	case PrimaryMuscleCalves:
		*s = PrimaryMuscleCalves
		return nil
	case PrimaryMuscleLegs:
		*s = PrimaryMuscleLegs
		return nil
	case PrimaryMuscleFullBody:
		*s = PrimaryMuscleFullBody
		return nil
	case PrimaryMuscleGrip:
		*s = PrimaryMuscleGrip
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
