// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *ErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

func (*ErrorResponse) getExercisesRes() {}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// Ref: #/components/schemas/Exercise
type Exercise struct {
	ID             uuid.UUID                    `json:"id"`
	Name           string                       `json:"name"`
	Category       ExerciseCategory             `json:"category"`
	Description    OptNilString                 `json:"description"`
	Instructions   []string                     `json:"instructions"`
	EquipmentTypes []ExerciseEquipmentTypesItem `json:"equipmentTypes"`
	PrimaryMuscles []ExercisePrimaryMusclesItem `json:"primaryMuscles"`
	Tags           []ExerciseTagsItem           `json:"tags"`
	CreatedAt      time.Time                    `json:"createdAt"`
	UpdatedAt      time.Time                    `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Exercise) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Exercise) GetName() string {
	return s.Name
}

// GetCategory returns the value of Category.
func (s *Exercise) GetCategory() ExerciseCategory {
	return s.Category
}

// GetDescription returns the value of Description.
func (s *Exercise) GetDescription() OptNilString {
	return s.Description
}

// GetInstructions returns the value of Instructions.
func (s *Exercise) GetInstructions() []string {
	return s.Instructions
}

// GetEquipmentTypes returns the value of EquipmentTypes.
func (s *Exercise) GetEquipmentTypes() []ExerciseEquipmentTypesItem {
	return s.EquipmentTypes
}

// GetPrimaryMuscles returns the value of PrimaryMuscles.
func (s *Exercise) GetPrimaryMuscles() []ExercisePrimaryMusclesItem {
	return s.PrimaryMuscles
}

// GetTags returns the value of Tags.
func (s *Exercise) GetTags() []ExerciseTagsItem {
	return s.Tags
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Exercise) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Exercise) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Exercise) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Exercise) SetName(val string) {
	s.Name = val
}

// SetCategory sets the value of Category.
func (s *Exercise) SetCategory(val ExerciseCategory) {
	s.Category = val
}

// SetDescription sets the value of Description.
func (s *Exercise) SetDescription(val OptNilString) {
	s.Description = val
}

// SetInstructions sets the value of Instructions.
func (s *Exercise) SetInstructions(val []string) {
	s.Instructions = val
}

// SetEquipmentTypes sets the value of EquipmentTypes.
func (s *Exercise) SetEquipmentTypes(val []ExerciseEquipmentTypesItem) {
	s.EquipmentTypes = val
}

// SetPrimaryMuscles sets the value of PrimaryMuscles.
func (s *Exercise) SetPrimaryMuscles(val []ExercisePrimaryMusclesItem) {
	s.PrimaryMuscles = val
}

// SetTags sets the value of Tags.
func (s *Exercise) SetTags(val []ExerciseTagsItem) {
	s.Tags = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Exercise) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Exercise) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

type ExerciseCategory string

const (
	ExerciseCategoryCardio     ExerciseCategory = "cardio"
	ExerciseCategoryStrength   ExerciseCategory = "strength"
	ExerciseCategoryPlyometric ExerciseCategory = "plyometric"
)

// AllValues returns all ExerciseCategory values.
func (ExerciseCategory) AllValues() []ExerciseCategory {
	return []ExerciseCategory{
		ExerciseCategoryCardio,
		ExerciseCategoryStrength,
		ExerciseCategoryPlyometric,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ExerciseCategory) MarshalText() ([]byte, error) {
	switch s {
	case ExerciseCategoryCardio:
		return []byte(s), nil
	case ExerciseCategoryStrength:
		return []byte(s), nil
	case ExerciseCategoryPlyometric:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ExerciseCategory) UnmarshalText(data []byte) error {
	switch ExerciseCategory(data) {
	case ExerciseCategoryCardio:
		*s = ExerciseCategoryCardio
		return nil
	case ExerciseCategoryStrength:
		*s = ExerciseCategoryStrength
		return nil
	case ExerciseCategoryPlyometric:
		*s = ExerciseCategoryPlyometric
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ExerciseEquipmentTypesItem string

const (
	ExerciseEquipmentTypesItemBodyweight    ExerciseEquipmentTypesItem = "bodyweight"
	ExerciseEquipmentTypesItemKettlebell    ExerciseEquipmentTypesItem = "kettlebell"
	ExerciseEquipmentTypesItemRowingMachine ExerciseEquipmentTypesItem = "rowing-machine"
	ExerciseEquipmentTypesItemSkiErg        ExerciseEquipmentTypesItem = "ski-erg"
	ExerciseEquipmentTypesItemMedicineBall  ExerciseEquipmentTypesItem = "medicine-ball"
	ExerciseEquipmentTypesItemDumbbells     ExerciseEquipmentTypesItem = "dumbbells"
	ExerciseEquipmentTypesItemBarbell       ExerciseEquipmentTypesItem = "barbell"
	ExerciseEquipmentTypesItemSled          ExerciseEquipmentTypesItem = "sled"
	ExerciseEquipmentTypesItemBox           ExerciseEquipmentTypesItem = "box"
	ExerciseEquipmentTypesItemJumpRope      ExerciseEquipmentTypesItem = "jump-rope"
	ExerciseEquipmentTypesItemAssaultBike   ExerciseEquipmentTypesItem = "assault-bike"
)

// AllValues returns all ExerciseEquipmentTypesItem values.
func (ExerciseEquipmentTypesItem) AllValues() []ExerciseEquipmentTypesItem {
	return []ExerciseEquipmentTypesItem{
		ExerciseEquipmentTypesItemBodyweight,
		ExerciseEquipmentTypesItemKettlebell,
		ExerciseEquipmentTypesItemRowingMachine,
		ExerciseEquipmentTypesItemSkiErg,
		ExerciseEquipmentTypesItemMedicineBall,
		ExerciseEquipmentTypesItemDumbbells,
		ExerciseEquipmentTypesItemBarbell,
		ExerciseEquipmentTypesItemSled,
		ExerciseEquipmentTypesItemBox,
		ExerciseEquipmentTypesItemJumpRope,
		ExerciseEquipmentTypesItemAssaultBike,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ExerciseEquipmentTypesItem) MarshalText() ([]byte, error) {
	switch s {
	case ExerciseEquipmentTypesItemBodyweight:
		return []byte(s), nil
	case ExerciseEquipmentTypesItemKettlebell:
		return []byte(s), nil
	case ExerciseEquipmentTypesItemRowingMachine:
		return []byte(s), nil
	case ExerciseEquipmentTypesItemSkiErg:
		return []byte(s), nil
	case ExerciseEquipmentTypesItemMedicineBall:
		return []byte(s), nil
	case ExerciseEquipmentTypesItemDumbbells:
		return []byte(s), nil
	case ExerciseEquipmentTypesItemBarbell:
		return []byte(s), nil
	case ExerciseEquipmentTypesItemSled:
		return []byte(s), nil
	case ExerciseEquipmentTypesItemBox:
		return []byte(s), nil
	case ExerciseEquipmentTypesItemJumpRope:
		return []byte(s), nil
	case ExerciseEquipmentTypesItemAssaultBike:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ExerciseEquipmentTypesItem) UnmarshalText(data []byte) error {
	switch ExerciseEquipmentTypesItem(data) {
	case ExerciseEquipmentTypesItemBodyweight:
		*s = ExerciseEquipmentTypesItemBodyweight
		return nil
	case ExerciseEquipmentTypesItemKettlebell:
		*s = ExerciseEquipmentTypesItemKettlebell
		return nil
	case ExerciseEquipmentTypesItemRowingMachine:
		*s = ExerciseEquipmentTypesItemRowingMachine
		return nil
	case ExerciseEquipmentTypesItemSkiErg:
		*s = ExerciseEquipmentTypesItemSkiErg
		return nil
	case ExerciseEquipmentTypesItemMedicineBall:
		*s = ExerciseEquipmentTypesItemMedicineBall
		return nil
	case ExerciseEquipmentTypesItemDumbbells:
		*s = ExerciseEquipmentTypesItemDumbbells
		return nil
	case ExerciseEquipmentTypesItemBarbell:
		*s = ExerciseEquipmentTypesItemBarbell
		return nil
	case ExerciseEquipmentTypesItemSled:
		*s = ExerciseEquipmentTypesItemSled
		return nil
	case ExerciseEquipmentTypesItemBox:
		*s = ExerciseEquipmentTypesItemBox
		return nil
	case ExerciseEquipmentTypesItemJumpRope:
		*s = ExerciseEquipmentTypesItemJumpRope
		return nil
	case ExerciseEquipmentTypesItemAssaultBike:
		*s = ExerciseEquipmentTypesItemAssaultBike
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ExercisePrimaryMusclesItem string

const (
	ExercisePrimaryMusclesItemChest      ExercisePrimaryMusclesItem = "chest"
	ExercisePrimaryMusclesItemBack       ExercisePrimaryMusclesItem = "back"
	ExercisePrimaryMusclesItemShoulders  ExercisePrimaryMusclesItem = "shoulders"
	ExercisePrimaryMusclesItemBiceps     ExercisePrimaryMusclesItem = "biceps"
	ExercisePrimaryMusclesItemTriceps    ExercisePrimaryMusclesItem = "triceps"
	ExercisePrimaryMusclesItemForearms   ExercisePrimaryMusclesItem = "forearms"
	ExercisePrimaryMusclesItemCore       ExercisePrimaryMusclesItem = "core"
	ExercisePrimaryMusclesItemAbs        ExercisePrimaryMusclesItem = "abs"
	ExercisePrimaryMusclesItemObliques   ExercisePrimaryMusclesItem = "obliques"
	ExercisePrimaryMusclesItemGlutes     ExercisePrimaryMusclesItem = "glutes"
	ExercisePrimaryMusclesItemQuads      ExercisePrimaryMusclesItem = "quads"
	ExercisePrimaryMusclesItemHamstrings ExercisePrimaryMusclesItem = "hamstrings"
	ExercisePrimaryMusclesItemCalves     ExercisePrimaryMusclesItem = "calves"
	ExercisePrimaryMusclesItemLegs       ExercisePrimaryMusclesItem = "legs"
	ExercisePrimaryMusclesItemFullBody   ExercisePrimaryMusclesItem = "full-body"
	ExercisePrimaryMusclesItemGrip       ExercisePrimaryMusclesItem = "grip"
)

// AllValues returns all ExercisePrimaryMusclesItem values.
func (ExercisePrimaryMusclesItem) AllValues() []ExercisePrimaryMusclesItem {
	return []ExercisePrimaryMusclesItem{
		ExercisePrimaryMusclesItemChest,
		ExercisePrimaryMusclesItemBack,
		ExercisePrimaryMusclesItemShoulders,
		ExercisePrimaryMusclesItemBiceps,
		ExercisePrimaryMusclesItemTriceps,
		ExercisePrimaryMusclesItemForearms,
		ExercisePrimaryMusclesItemCore,
		ExercisePrimaryMusclesItemAbs,
		ExercisePrimaryMusclesItemObliques,
		ExercisePrimaryMusclesItemGlutes,
		ExercisePrimaryMusclesItemQuads,
		ExercisePrimaryMusclesItemHamstrings,
		ExercisePrimaryMusclesItemCalves,
		ExercisePrimaryMusclesItemLegs,
		ExercisePrimaryMusclesItemFullBody,
		ExercisePrimaryMusclesItemGrip,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ExercisePrimaryMusclesItem) MarshalText() ([]byte, error) {
	switch s {
	case ExercisePrimaryMusclesItemChest:
		return []byte(s), nil
	case ExercisePrimaryMusclesItemBack:
		return []byte(s), nil
	case ExercisePrimaryMusclesItemShoulders:
		return []byte(s), nil
	case ExercisePrimaryMusclesItemBiceps:
		return []byte(s), nil
	case ExercisePrimaryMusclesItemTriceps:
		return []byte(s), nil
	case ExercisePrimaryMusclesItemForearms:
		return []byte(s), nil
	case ExercisePrimaryMusclesItemCore:
		return []byte(s), nil
	case ExercisePrimaryMusclesItemAbs:
		return []byte(s), nil
	case ExercisePrimaryMusclesItemObliques:
		return []byte(s), nil
	case ExercisePrimaryMusclesItemGlutes:
		return []byte(s), nil
	case ExercisePrimaryMusclesItemQuads:
		return []byte(s), nil
	case ExercisePrimaryMusclesItemHamstrings:
		return []byte(s), nil
	case ExercisePrimaryMusclesItemCalves:
		return []byte(s), nil
	case ExercisePrimaryMusclesItemLegs:
		return []byte(s), nil
	case ExercisePrimaryMusclesItemFullBody:
		return []byte(s), nil
	case ExercisePrimaryMusclesItemGrip:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ExercisePrimaryMusclesItem) UnmarshalText(data []byte) error {
	switch ExercisePrimaryMusclesItem(data) {
	case ExercisePrimaryMusclesItemChest:
		*s = ExercisePrimaryMusclesItemChest
		return nil
	case ExercisePrimaryMusclesItemBack:
		*s = ExercisePrimaryMusclesItemBack
		return nil
	case ExercisePrimaryMusclesItemShoulders:
		*s = ExercisePrimaryMusclesItemShoulders
		return nil
	case ExercisePrimaryMusclesItemBiceps:
		*s = ExercisePrimaryMusclesItemBiceps
		return nil
	case ExercisePrimaryMusclesItemTriceps:
		*s = ExercisePrimaryMusclesItemTriceps
		return nil
	case ExercisePrimaryMusclesItemForearms:
		*s = ExercisePrimaryMusclesItemForearms
		return nil
	case ExercisePrimaryMusclesItemCore:
		*s = ExercisePrimaryMusclesItemCore
		return nil
	case ExercisePrimaryMusclesItemAbs:
		*s = ExercisePrimaryMusclesItemAbs
		return nil
	case ExercisePrimaryMusclesItemObliques:
		*s = ExercisePrimaryMusclesItemObliques
		return nil
	case ExercisePrimaryMusclesItemGlutes:
		*s = ExercisePrimaryMusclesItemGlutes
		return nil
	case ExercisePrimaryMusclesItemQuads:
		*s = ExercisePrimaryMusclesItemQuads
		return nil
	case ExercisePrimaryMusclesItemHamstrings:
		*s = ExercisePrimaryMusclesItemHamstrings
		return nil
	case ExercisePrimaryMusclesItemCalves:
		*s = ExercisePrimaryMusclesItemCalves
		return nil
	case ExercisePrimaryMusclesItemLegs:
		*s = ExercisePrimaryMusclesItemLegs
		return nil
	case ExercisePrimaryMusclesItemFullBody:
		*s = ExercisePrimaryMusclesItemFullBody
		return nil
	case ExercisePrimaryMusclesItemGrip:
		*s = ExercisePrimaryMusclesItemGrip
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ExerciseResponse
type ExerciseResponse struct {
	Data []Exercise `json:"data"`
}

// GetData returns the value of Data.
func (s *ExerciseResponse) GetData() []Exercise {
	return s.Data
}

// SetData sets the value of Data.
func (s *ExerciseResponse) SetData(val []Exercise) {
	s.Data = val
}

func (*ExerciseResponse) getExercisesRes() {}

type ExerciseTagsItem string

const (
	ExerciseTagsItemCrossfit          ExerciseTagsItem = "crossfit"
	ExerciseTagsItemHyrox             ExerciseTagsItem = "hyrox"
	ExerciseTagsItemBeginnerFriendly  ExerciseTagsItem = "beginner-friendly"
	ExerciseTagsItemAdvanced          ExerciseTagsItem = "advanced"
	ExerciseTagsItemConditioning      ExerciseTagsItem = "conditioning"
	ExerciseTagsItemStrengthEndurance ExerciseTagsItem = "strength-endurance"
	ExerciseTagsItemPower             ExerciseTagsItem = "power"
	ExerciseTagsItemCore              ExerciseTagsItem = "core"
	ExerciseTagsItemFunctional        ExerciseTagsItem = "functional"
	ExerciseTagsItemCompetition       ExerciseTagsItem = "competition"
	ExerciseTagsItemPlyometric        ExerciseTagsItem = "plyometric"
)

// AllValues returns all ExerciseTagsItem values.
func (ExerciseTagsItem) AllValues() []ExerciseTagsItem {
	return []ExerciseTagsItem{
		ExerciseTagsItemCrossfit,
		ExerciseTagsItemHyrox,
		ExerciseTagsItemBeginnerFriendly,
		ExerciseTagsItemAdvanced,
		ExerciseTagsItemConditioning,
		ExerciseTagsItemStrengthEndurance,
		ExerciseTagsItemPower,
		ExerciseTagsItemCore,
		ExerciseTagsItemFunctional,
		ExerciseTagsItemCompetition,
		ExerciseTagsItemPlyometric,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ExerciseTagsItem) MarshalText() ([]byte, error) {
	switch s {
	case ExerciseTagsItemCrossfit:
		return []byte(s), nil
	case ExerciseTagsItemHyrox:
		return []byte(s), nil
	case ExerciseTagsItemBeginnerFriendly:
		return []byte(s), nil
	case ExerciseTagsItemAdvanced:
		return []byte(s), nil
	case ExerciseTagsItemConditioning:
		return []byte(s), nil
	case ExerciseTagsItemStrengthEndurance:
		return []byte(s), nil
	case ExerciseTagsItemPower:
		return []byte(s), nil
	case ExerciseTagsItemCore:
		return []byte(s), nil
	case ExerciseTagsItemFunctional:
		return []byte(s), nil
	case ExerciseTagsItemCompetition:
		return []byte(s), nil
	case ExerciseTagsItemPlyometric:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ExerciseTagsItem) UnmarshalText(data []byte) error {
	switch ExerciseTagsItem(data) {
	case ExerciseTagsItemCrossfit:
		*s = ExerciseTagsItemCrossfit
		return nil
	case ExerciseTagsItemHyrox:
		*s = ExerciseTagsItemHyrox
		return nil
	case ExerciseTagsItemBeginnerFriendly:
		*s = ExerciseTagsItemBeginnerFriendly
		return nil
	case ExerciseTagsItemAdvanced:
		*s = ExerciseTagsItemAdvanced
		return nil
	case ExerciseTagsItemConditioning:
		*s = ExerciseTagsItemConditioning
		return nil
	case ExerciseTagsItemStrengthEndurance:
		*s = ExerciseTagsItemStrengthEndurance
		return nil
	case ExerciseTagsItemPower:
		*s = ExerciseTagsItemPower
		return nil
	case ExerciseTagsItemCore:
		*s = ExerciseTagsItemCore
		return nil
	case ExerciseTagsItemFunctional:
		*s = ExerciseTagsItemFunctional
		return nil
	case ExerciseTagsItemCompetition:
		*s = ExerciseTagsItemCompetition
		return nil
	case ExerciseTagsItemPlyometric:
		*s = ExerciseTagsItemPlyometric
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type GetExercisesCategory string

const (
	GetExercisesCategoryCardio     GetExercisesCategory = "cardio"
	GetExercisesCategoryStrength   GetExercisesCategory = "strength"
	GetExercisesCategoryPlyometric GetExercisesCategory = "plyometric"
)

// AllValues returns all GetExercisesCategory values.
func (GetExercisesCategory) AllValues() []GetExercisesCategory {
	return []GetExercisesCategory{
		GetExercisesCategoryCardio,
		GetExercisesCategoryStrength,
		GetExercisesCategoryPlyometric,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetExercisesCategory) MarshalText() ([]byte, error) {
	switch s {
	case GetExercisesCategoryCardio:
		return []byte(s), nil
	case GetExercisesCategoryStrength:
		return []byte(s), nil
	case GetExercisesCategoryPlyometric:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetExercisesCategory) UnmarshalText(data []byte) error {
	switch GetExercisesCategory(data) {
	case GetExercisesCategoryCardio:
		*s = GetExercisesCategoryCardio
		return nil
	case GetExercisesCategoryStrength:
		*s = GetExercisesCategoryStrength
		return nil
	case GetExercisesCategoryPlyometric:
		*s = GetExercisesCategoryPlyometric
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptGetExercisesCategory returns new OptGetExercisesCategory with value set to v.
func NewOptGetExercisesCategory(v GetExercisesCategory) OptGetExercisesCategory {
	return OptGetExercisesCategory{
		Value: v,
		Set:   true,
	}
}

// OptGetExercisesCategory is optional GetExercisesCategory.
type OptGetExercisesCategory struct {
	Value GetExercisesCategory
	Set   bool
}

// IsSet returns true if OptGetExercisesCategory was set.
func (o OptGetExercisesCategory) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptGetExercisesCategory) Reset() {
	var v GetExercisesCategory
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptGetExercisesCategory) SetTo(v GetExercisesCategory) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptGetExercisesCategory) Get() (v GetExercisesCategory, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptGetExercisesCategory) Or(d GetExercisesCategory) GetExercisesCategory {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
